@WebApi_HostAddress = https://localhost:7092

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/todo/complete

###

GET {{WebApi_HostAddress}}/api/todo

###

GET {{WebApi_HostAddress}}/api/todo/1

###

GET {{WebApi_HostAddress}}/api/todo/0

###