@WebApi_HostAddress = https://localhost:7092

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/todo
Content-Type: application/json

{
  "Description" : "A",
  "IsComplete" : true
}

###

GET {{WebApi_HostAddress}}/api/todo/complete

###

GET {{WebApi_HostAddress}}/api/todo

###

GET {{WebApi_HostAddress}}/api/todo/1

###

GET {{WebApi_HostAddress}}/api/todo/0

###

PUT {{WebApi_HostAddress}}/api/todo/1
Content-Type: application/json

{
  "Id" : 1,
  "Description" : "A Updated",
  "IsComplete" : false
}

###
PUT {{WebApi_HostAddress}}/api/todo/0
Content-Type: application/json

{
  "Id" : 1,
  "Description" : "A",
  "IsComplete" : true
}

###
PUT {{WebApi_HostAddress}}/api/todo/0
Content-Type: application/json

{
  "Id" : 0
  "Description" : "A",
  "IsComplete" : true
}

###

DELETE {{WebApi_HostAddress}}/api/todo/1

###
DELETE {{WebApi_HostAddress}}/api/todo/0

###
